/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package io.wonderland.alice.asn1.caesar;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class CaesarKeyASN1 extends BerInteger {

  private static final long serialVersionUID = 1L;

  public CaesarKeyASN1() {
  }

  public CaesarKeyASN1(byte[] code) {
    super(code);
  }

  public CaesarKeyASN1(BigInteger value) {
    super(value);
  }

  public CaesarKeyASN1(long value) {
    super(value);
  }

}
