name: rabbit-hole
version: '0.0.1'
summary: Cryptography application
description: |
  rabbit-hole is an application integrating different cryptographic libraries.
  Some features include:
  - Ciphers (encrypt & decrypt)
  - Hash (hashing)
  - MAC (generation)
  - Key / KeyPair (generation & export)
  - KeyStore (loading & reading)
  - Code points & Codecs with different bases
  - Barcode (generation)


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22 # the base snap is the execution environment for this snap


title: rabbit-hole
website: https://github.com/gentjankolicaj/wonderland
issues: https://github.com/gentjankolicaj/wonderland/issues
license: GPL-3.0

# Enable faster LZO compression
compression: lzo

parts:
  artifact-setup:
    plugin: dump
    source: .
    organize:
      download_artifacts.sh: download_artifacts.sh
    build-packages:
      - unzip
      - curl
    override-build: |
      sh ./download_artifacts.sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      echo '#!/bin/sh' > $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-launch
      echo 'exec $SNAP/usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar $SNAP/*shaded.jar' >> $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-launch
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-launch
  jre:
    after: [ artifact-setup ]
    plugin: nil
    stage-packages:
      - openjdk-17-jdk

apps:
  rabbit-hole:
    command: $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-launch
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - opengl
      - wayland
      - x11