/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package io.wonderland.alice.asn1.railfence;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class RailfenceKeyASN1 extends BerInteger {

  private static final long serialVersionUID = 1L;

  public RailfenceKeyASN1() {
  }

  public RailfenceKeyASN1(byte[] code) {
    super(code);
  }

  public RailfenceKeyASN1(BigInteger value) {
    super(value);
  }

  public RailfenceKeyASN1(long value) {
    super(value);
  }

}
