name: rabbit-hole
version: '0.0.1'
summary: A cryptography application
description: |
  rabbit-hole is a cross-platform desktop application integrating different CSP in Java JCA.
  
  Some features of this application are :
  - Cipher tab for encrypting,decrypting. 
  - Hash tab for hashing.
  - MAC tab for mac-ing.
  - Key tab for secret-key/public-key generating & exporting.
  - KeyStore tab for keystore loading & reading.
  - CodePoint tab for code-point reading.
  - Barcode tab for barcode generating.
  - Codecs for encode/decode in different bases
  - etc..


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core22 # the base snap is the execution environment for this snap

title: rabbit-hole
website: https://github.com/gentjankolicaj/wonderland
issues: https://github.com/gentjankolicaj/wonderland/issues


lint:
  ignore:
    - library:
        - usr/lib/jvm/java-*/lib/*.so

parts:
  artifact-setup:
    plugin: dump
    source: local/

    build-packages:
      - unzip
      - curl
      - ca-certificates
      - ca-certificates-java

    override-build: |
      craftctl default
      sh ./download_artifacts.sh
      echo $CRAFT_PART_INSTALL/bin/
      mkdir -p $CRAFT_PART_INSTALL/jar
      cp ./*shaded.jar $CRAFT_PART_INSTALL/jar
      echo 'Finished copying app jar'
      chmod +x ./rabbit-hole.launcher
      echo 'rabbit-hole.launcher set x permission'

    stage-packages:
      - openjdk-17-jre
      - libcanberra-gtk3-module
      - libcanberra-gtk-module

apps:
  rabbit-hole:
    extensions:
      [ gnome ]
    command: rabbit-hole.launcher
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind
      - network-observe
      - system-observe
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
