name: rabbit-hole
version: '0.0.1'
summary: cryptography application
description: |
  rabbit-hole is a application integrating different cryptographic libraries.
  Some of features include :
  - Ciphers ( encrypt & decrypt )
  - Hash ( hashing)
  - MAC ( generation )
  - Key / KeyPair ( generation & export )
  - KeyStore ( loading & reading )
  - Code points & Codecs with different bases
  - Barcode ( generation )


grade: devel
confinement: devmode
base: core22

title: rabbit-hole
website: https://github.com/gentjankolicaj/wonderland
issues: https://github.com/gentjankolicaj/wonderland/issues
license: GPL-3.0

# Enable faster LZO compression
compression: lzo

# Ignore useless library warnings
lint:
  ignore:
    - library

apps:
  rabbit-hole-app:
    command: bin/rabbit-hole
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl

parts:
  rabbit-hole-app:
    plugin: maven
    source: https://github.com/gentjankolicaj/wonderland.git
    source-branch: master
    source-type: git
    build-packages:
      - maven
      - openjdk-17-jdk-headless
    stage-packages:
      - openjdk-17-jre-headless
    override-build: |
      mvn clean package -DskipTest=true -f ../pom.xml
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp ../rabbit-hole/target/*shaded.jar $SNAPCRAFT_PART_INSTALL/lib/rabbit-hole-app.jar
      echo '#!/bin/sh' > $SNAPCRAFT_PART_INSTALL/bin/app.jar
      echo 'exec $SNAP/usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar $SNAP/lib/rabbit-hole-app.jar' >> $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-app
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/rabbit-hole-app
      mvn clean -f ../pom.xml

  jdk:
    plugin: nil
    stage-packages:
      - openjdk-17-jre