name: rabbit-hole
version: '0.0.1'
summary: cryptography application
description: |
  rabbit-hole is a application using different cryptographic libraries.Ciphers,Hash,Mac...etc included.

grade: stable
confinement: devmode
base: core22

title: rabbit-hole
website: https://github.com/gentjankolicaj/wonderland
issues: https://github.com/gentjankolicaj/wonderland/issues
license: GPL-3.0

# Enable faster LZO compression
compression: lzo

# Ignore useless library warnings
lint:
  ignore:
    - library

apps:
  rabbit-hole:
    command: rh-wrapper
    plugs:
      - home
      - network
      - network-bind

parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local

    build-packages:
      - maven
      - openjdk-11-jdk-headless

  rabbit-hole:
    plugin: maven
    source: https://github.com/gentjankolicaj/wonderland.git
    source-branch: master
    source-type: git

    build-packages:
      - maven
      - openjdk-17-jdk-headless

    stage-packages:
      - openjdk-17-jre-headless

    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-17-openjdk-*/lib/security/blacklisted.certs